Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"

  # Provisioning scripts
  config.vm.provision :shell, path: "bootstrap.sh"

  # Networking configurations
  config.vm.network "private_network", ip: "192.168.56.110"

  # Set hostname
  config.vm.hostname = "roaraujoS"

  # Set resources for VirtualBox (RAM and CPU)
  config.vm.define "roaraujoS-vm" do |vm|
    vm.vm.provider "virtualbox" do |vb|
      vb.memory = "512"  # 512MB of RAM
      vb.cpus = 1        # 1 CPU
    end
  end

  # Miscellaneous
  # config.vbguest.auto_update = false  # Ignores version check for Guest Additions
end
