# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # Use the latest stable Alpine Linux box
  config.vm.box = "alpine/alpine64"
  config.vm.box_version = "3.7.0"

  # Defne the VM (controller)
  config.vm.define "roaraujoS" do |control|
    control.vm.hostname = "roaraujoS"
    control.vm.network "private_network", ip: "192.168.56.110"

    control.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "roaraujoS"]
      v.memory = 512
      v.cpus = 1
    end

    # Provisioning with inline shell script
    config.vm.provision "shell", inline: <<-SHELL
      echo "Configuring roaraujoS as the controller"
      # Insert commands for configuring K3s here
    SHELL

    # Optional: Additional provisioning via external script
    # control.vm.provision "shell", path: "path/to/controller.sh"
  end

  # Define the second VM (agent)
  config.vm.define "roaraujoSW" do |agent|
    agent.vm.hostname = "roaraujoSW"
    agent.vm.network "private_network", ip: "192.168.56.111"

    agent.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "roaraujoSW"]
      v.memory = 512
      v.cpus = 1
    end

    # Provisioning with inline shell script
    agent.vm.provision "shell", inline: <<-SHELL
      echo "Configuring roaraujoSW as the agent"
    SHELL

    # Optional: Additional provisioning via external script
    # agent.vm.provision "shell", path: "path/to/agent_setup.sh"
  end
end
