Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"

  ######################
  # K3s Server VM
  ######################
  config.vm.define "roaraujoS" do |server|
    server.vm.hostname = "roaraujoS"
    server.vm.network "private_network", ip: "192.168.56.110"
    
    # Configure VM capacity
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    
    # Provision k3s in server mode via external script
    server.vm.provision "shell", path: "scripts/server-setup.sh"
  end

  ######################
  # K3s Agent VM
  ######################
  config.vm.define "roaraujoSW" do |agent|
    agent.vm.hostname = "roaraujoSW"
    agent.vm.network "private_network", ip: "192.168.56.111"
    
    # Configure VM capacity
    agent.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end

    # Provision k3s in agent mode via external script
    agent.vm.provision "shell", path: "scripts/agent-setup.sh"
    end

end
