Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.box_version = "20241002.0.0"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
  end

  config.vm.define "roaraujoS" do |s|
    s.vm.hostname = "roaraujoS"
    s.vm.network "private_network", ip: "192.168.56.110"
  end

  config.vm.define "roaraujoSW" do |sw|
    sw.vm.hostname = "roaraujoSW"
    sw.vm.network "private_network", ip: "192.168.56.111"
  end

end
